spring.application.name=Parking-lot
spring.profiles.active=h2

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Parking lot configuration
# Pricing Strategy: HOURLY, DAILY, FLAT_RATE
parking.pricing-strategy=HOURLY

# Slot Allocation Strategy: FIRST_FIT, NEAREST_FIT
parking.slot-allocation-strategy=FIRST_FIT

